### ISSUE TITLE
[🐛 Bug]: victoriametrics provider "Failed to get alerts"

### ISSUE THREAD

**Issue by aksenk** [keephq/keep#4383]
**Describe the bug**
I have connected victoriametrics as a connected provider.

The UI says that it has connected successfully.

but the alerts are received with an error.

I see the following errors in the backend logs

```	
{"worker_type": "uvicorn", "asctime": "2025-04-02 18:42:32,118", "message": "Unknown error pulling from provider victoriametrics (796067b5aef445d899d65a685e49e3de)", "levelname": "ERROR", "name": "keep.api.routes.preset", "filename": "preset.py", "otelTraceID": "969bfe4af3e2077c541e30dfbc9b3cbb", "otelSpanID": "323c316b0db92cca", "otelTraceSampled": true, "otelServiceName": "keep-api", "threadName": "AnyIO worker thread", "process": 18, "module": "preset", "exc_info": "Traceback (most recent call last):\n  File \"/venv/lib/python3.11/site-packages/keep/api/routes/preset.py\", line 116, in pull_data_from_providers\n    provider_class.get_alerts_by_fingerprint(tenant_id=tenant_id)\n  File \"/venv/lib/python3.11/site-packages/keep/providers/base/base_provider.py\", line 519, in get_alerts_by_fingerprint\n    alerts = self.get_alerts()\n             ^^^^^^^^^^^^^^^^^\n  File \"/venv/lib/python3.11/site-packages/keep/providers/base/base_provider.py\", line 504, in get_alerts\n    alerts = self._get_alerts()\n             ^^^^^^^^^^^^^^^^^^\n  File \"/venv/lib/python3.11/site-packages/keep/providers/victoriametrics_provider/victoriametrics_provider.py\", line 469, in _get_alerts\n    raise e\n  File \"/venv/lib/python3.11/site-packages/keep/providers/victoriametrics_provider/victoriametrics_provider.py\", line 456, in _get_alerts\n    severity=VictoriametricsProvider.SEVERITIES_MAP[\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nKeyError: 'none'", "provider_type": "victoriametrics", "provider_id": "796067b5aef445d899d65a685e49e3de", "tenant_id": "keep", "trace_id": "969bfe4af3e2077c541e30dfbc9b3cbb", "exception": "'none'"}
	
{"worker_type": "uvicorn", "asctime": "2025-04-02 18:42:32,111", "message": "Failed to get alerts", "levelname": "ERROR", "name": "provider.796067b5aef445d899d65a685e49e3de", "filename": "victoriametrics_provider.py", "otelTraceID": "969bfe4af3e2077c541e30dfbc9b3cbb", "otelSpanID": "8329e8a2f644329d", "otelTraceSampled": true, "otelServiceName": "keep-api", "threadName": "AnyIO worker thread", "process": 18, "module": "victoriametrics_provider", "exc_info": "Traceback (most recent call last):\n  File \"/venv/lib/python3.11/site-packages/keep/providers/victoriametrics_provider/victoriametrics_provider.py\", line 456, in _get_alerts\n    severity=VictoriametricsProvider.SEVERITIES_MAP[\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nKeyError: 'none'", "tenant_id": "keep", "provider_id": "796067b5aef445d899d65a685e49e3de", "execution_id": "5b2e9137-e928-400a-9086-3894802cf97c"}
```

**To Reproduce**

1. Go to providers section in UI
2. Add victoriametrics provider via vmalert config (in my k8s cluster it is `http://vmalert-victoria-metrics.victoria-metrics:8080`
3. Wait for pulling
4. See error in UI (`Provider Logs`) and backend pod logs

**Expected behavior**
Alerts was scraped successfully

**Screenshots**
<img width="559" alt="Image" src="https://github.com/user-attachments/assets/51cd01e8-e17c-454f-a75a-28db2eed0c79" />

**Comment by talboren** [comment]
Thank you for the issue @aksenk  
We will fix it by tomorrow!

**Comment by talboren** [comment]
@aksenk I think the draft PR @Matvey-Kuk created should fix that

**Comment by talboren** [comment]
> [@talboren](https://github.com/talboren) thanks!
> 
> Do you not update the chart version after updating the app version?

I’ll make sure it’s updated by tomorrow

**Comment by aksenk** [comment]
I try new app version (just change image.tag in helm chart) and it's work. thanks!

**Comment by aksenk** [comment]
but in database still exist old provider, it is OK? (rename `vms` -> `victoriametrics`)

```
-[ RECORD 1 ]-----+------------------------------------------------------
validatedScopes   | {}
id                | cd4df4ec5ca4498abdae8f54f1ce4877
tenant_id         | keep
name              | vms
description       |
type              | victoriametrics
installed_by      | system
installation_time | 2025-04-03 14:11:03.198118
configuration_key | keep_victoriametrics_cd4df4ec5ca4498abdae8f54f1ce4877
consumer          | f
last_pull_time    | 2025-04-03 15:13:19.669075
provisioned       | t
pulling_enabled   | t
-[ RECORD 2 ]-----+------------------------------------------------------
validatedScopes   | {}
id                | 8c5ed459ec064699a2a8babc12142339
tenant_id         | keep
name              | victoriametrics
description       |
type              | victoriametrics
installed_by      | system
installation_time | 2025-04-03 16:48:57.705686
configuration_key | keep_victoriametrics_8c5ed459ec064699a2a8babc12142339
consumer          | f
last_pull_time    | 2025-04-03 16:50:31.975431
provisioned       | t
pulling_enabled   | t
```

**Comment by aksenk** [comment]
@talboren I use latest version (0.41.5) but the problem still exist

logs:

```
{"worker_type": "uvicorn", "asctime": "2025-04-03 17:39:34,680", "message": "Failed to get alerts", "levelname": "ERROR", "name": "provider.0f7c365d33434024b0095dd2da335b08", "filename": "victoriametrics_provider.py", "otelTraceID": "b2a1a478f67a3d4963b92a9df8187706", "otelSpanID": "b48b7a03d3462f9c", "otelTraceSampled": true, "otelServiceName": "keep-api", "threadName": "AnyIO worker thread", "process": 18, "module": "victoriametrics_provider", "exc_info": "Traceback (most recent call last):\n  File \"/venv/lib/python3.11/site-packages/keep/providers/victoriametrics_provider/victoriametrics_provider.py\", line 456, in _get_alerts\n    severity=VictoriametricsProvider.SEVERITIES_MAP[\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nKeyError: 'none'", "tenant_id": "keep", "provider_id": "0f7c365d33434024b0095dd2da335b08", "execution_id": "da797e5b-ed29-4a8f-96bc-9a31eb89ef84"}

{"worker_type": "uvicorn", "asctime": "2025-04-03 17:39:34,686", "message": "Unknown error pulling from provider victoriametrics (0f7c365d33434024b0095dd2da335b08)", "levelname": "ERROR", "name": "keep.api.routes.preset", "filename": "preset.py", "otelTraceID": "b2a1a478f67a3d4963b92a9df8187706", "otelSpanID": "c25c8a25f38d301b", "otelTraceSampled": true, "otelServiceName": "keep-api", "threadName": "AnyIO worker thread", "process": 18, "module": "preset", "exc_info": "Traceback (most recent call last):\n  File \"/venv/lib/python3.11/site-packages/keep/api/routes/preset.py\", line 116, in pull_data_from_providers\n    provider_class.get_alerts_by_fingerprint(tenant_id=tenant_id)\n  File \"/venv/lib/python3.11/site-packages/keep/providers/base/base_provider.py\", line 535, in get_alerts_by_fingerprint\n    alerts = self.get_alerts()\n             ^^^^^^^^^^^^^^^^^\n  File \"/venv/lib/python3.11/site-packages/keep/providers/base/base_provider.py\", line 520, in get_alerts\n    alerts = self._get_alerts()\n             ^^^^^^^^^^^^^^^^^^\n  File \"/venv/lib/python3.11/site-packages/keep/providers/victoriametrics_provider/victoriametrics_provider.py\", line 469, in _get_alerts\n    raise e\n  File \"/venv/lib/python3.11/site-packages/keep/providers/victoriametrics_provider/victoriametrics_provider.py\", line 456, in _get_alerts\n    severity=VictoriametricsProvider.SEVERITIES_MAP[\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nKeyError: 'none'", "provider_type": "victoriametrics", "provider_id": "0f7c365d33434024b0095dd2da335b08", "tenant_id": "keep", "trace_id": "b2a1a478f67a3d4963b92a9df8187706", "exception": "'none'"}
```

**Comment by talboren** [comment]
@aksenk it hasn't been merged yet, should be soon: https://github.com/keephq/keep/pull/4363 and we will release a new version tomorrow/Sunday. After it's merged, you can use latest.
